### ISSUE TITLE
Lookups for non-existent users return 500 status

### ISSUE THREAD

**Issue by JCallicoat** [Ryuujinx/pad_calc#1]
[Fri 01:33 AM] ~ $ curl -I http://pad.allthings.moe/lookup/foobarbaz
HTTP/1.1 500 Internal Server Error

Please to fix!

**Comment by SharaaEsper** [comment]
Fixed in commits 4fc51eb1a628272379692daea8d0bc1b93844a48 & df9045e3a6eef609f7a790a472d7d12b32f7ab66

Closing issue.
